//
//  Constants.swift
//  Wicca
//
//  Created by Jay Jariwala on 26/01/21.
//  Copyright © 2021 Jay Jariwala. All rights reserved.
//

import Foundation

var isLifetimeTrial: Bool = false
var isMonthlyTrial: Bool = false
var LifetimeTrialDays: Int = 0
var monthlyTrialDays: Int = 0

let KRefreshPage = Notification.Name("KRefreshPage")
let kPurchasingPremiumPlan = NSNotification.Name("KPurchasingPremiumPlan")
let kFailPurchasingPremiumPlan = NSNotification.Name("kFailPurchasingPremiumPlan")
let kCompletePurchasingPremiumPlan = NSNotification.Name("kCompletePurchasingPremiumPlan")
let kUpdateRestoreButtonUI = NSNotification.Name("UpdateRestoreButtonUI")
enum APP_KEYS {
    static let kPremiumUser = "premiumUser"
    static let kUnlockWiccaPrice = "kUnlockWiccaPrice"
    static let kUnlockWiccaLocalePrice = "kUnlockWiccaLocalePrice"
    static let kUnlockWiccaLifetimePrice = "kUnlockWiccaLifetimePrice"
    static let kUnlockWiccaLifetimeLocalePrice = "kUnlockWiccaLifetimeLocalePrice"
    static let kUnlockWiccaMonthlyPrice = "kUnlockWiccaMonthlyPrice"
    static let kUnlockWiccaMonthlyLocalePrice = "kUnlockWiccaMonthlyLocalePrice"
    static let kNeverPurchasePlan = "neverPurchasePlan"
    static let kExpirePlan = "expirePlan"
}

enum Purpose: String {
    case Spells = "Spells"
    case HerbsAndOils = "HerbsAndOils"
    case Calendar = "Calendar"
    case CandleColors = "CandleColors"
    case LunarCalendar = "LunarCalendar"
}

let SpellsCategory: [SpellCategoryModel] = [
    SpellCategoryModel.init(categoryId: 0, categoryName: "Advice Spells"),
    SpellCategoryModel.init(categoryId: 1, categoryName: "Arguments Spells"),
    SpellCategoryModel.init(categoryId: 2, categoryName: "Blessings Spells"),
    SpellCategoryModel.init(categoryId: 3, categoryName: "Business Spells"),
    SpellCategoryModel.init(categoryId: 4, categoryName: "Career and Job Spells"),
    SpellCategoryModel.init(categoryId: 5, categoryName: "Courage Spells"),
    SpellCategoryModel.init(categoryId: 6, categoryName: "Forgiveness Spells"),
    SpellCategoryModel.init(categoryId: 7, categoryName: "Friendship Spells"),
    SpellCategoryModel.init(categoryId: 8, categoryName: "Gossip Spells"),
    SpellCategoryModel.init(categoryId: 9, categoryName: "Gratitude Spells"),
    SpellCategoryModel.init(categoryId: 10, categoryName: "Health Spells"),
    SpellCategoryModel.init(categoryId: 11, categoryName: "House Blessing Spells"),
    SpellCategoryModel.init(categoryId: 12, categoryName: "Inspiration Spells"),
    SpellCategoryModel.init(categoryId: 13, categoryName: "Kindness Spells"),
    SpellCategoryModel.init(categoryId: 14, categoryName: "Loneliness Spells"),
    SpellCategoryModel.init(categoryId: 15, categoryName: "Lost Items Spells"),
    SpellCategoryModel.init(categoryId: 16, categoryName: "Love Spells"),
    SpellCategoryModel.init(categoryId: 17, categoryName: "Luck Spells"),
    SpellCategoryModel.init(categoryId: 18, categoryName: "Miscellaneous Spells"),
    SpellCategoryModel.init(categoryId: 19, categoryName: "Peace Spells"),
    SpellCategoryModel.init(categoryId: 20, categoryName: "Pet Spells"),
    SpellCategoryModel.init(categoryId: 21, categoryName: "Problem Solving Spells"),
    SpellCategoryModel.init(categoryId: 22, categoryName: "Prosperity Spell"),
    SpellCategoryModel.init(categoryId: 23, categoryName: "Protection Spells"),
    SpellCategoryModel.init(categoryId: 24, categoryName: "Self Esteem Spells"),
    SpellCategoryModel.init(categoryId: 25, categoryName: "Travelling Spells")
]

let SubCategory: [SpellModel] = [
    /// `Advice Spells`
    SpellModel.init(categoryId: 0, spellId: 0, spellName: "Give Advice", spellContent: "Ingredients:\n\nSome white chrysanthemums or other seasonal flowers\nA sprig or two of parsley\nA malachite crystal\nA white altar candle\nA green taper candle\nA silver pen\nSilver ink\nWriting paper A fireproof dish\n\nUse the silver pen and ink to write a favourite verse or prayer on the paper, before picking up the malachite crystal and holding it tightly in one hand. Focus on it and silently ask that you be blessed with the ability to listen to what is said to you with compassion and understanding and that you may speak with assurance and wisdom. Ask that your mouth, ears and throat be blessed. Now light the green candle and use its flame to set fire to the paper on which you have inscribed the verse or prayer. Put the burning paper in the fireproof dish, stand facing the altar and with arms raised above your head, say:\n\nPlease listen to the words I say,\nAnd hear me now as I do pray.\nMay wisdom bless my tongue and lips,\nAnd guidance bless advice I give.\nAnd let it be done, that it harm no one."),
    /// `Arguments Spells`
    SpellModel.init(categoryId: 1, spellId: 1, spellName: "Restore Friendship", spellContent: "Ingredients:\n\nAn old scarf long enough to go right round the tree\n\nHolding the scarf in your hand you pass through the cleft in the tree nine times counter-clockwise saying:\n\nWhere there is pain,\nLet friendship now reign.\nAnd let it be done, that it harm no one.\n\nIf you cannot climb through the tree, simply walk around it.\n\nNow do the same again, nine times clockwise,saying:\n\nMay bitterness end,\nAnd ill feelings mend.\nAnd let it be done, that it harm no one.\n\nNow loop the scarf right round the tree and tie three knots to bind the ends together. As you tie the knots say:\n\nKnot one, sorrow end.\nKnot two, be us friend\nKnot three, heal the pain,\nLet love flow again.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 1, spellId: 2, spellName: "Burying the Hatchet", spellContent: "Ingredients:\n\nA sapling tree or a young shrub that will grow to a fair size in maturity\nAn unused hatchet\nRibbons of the astrological colours appropriate to each member of the family or those involved in the friendship\nA strand of hair from each person\nA spade\n\nDig a hole deep enough to support the sapling or shrub and drop the hairs into the bottom. As each one goes in, visualize the ill feeling in that person (not forgetting your own) evaporating and being replaced by good will. Now tie the ribbons round the hatchet and ask everyone to form a circle round the hole. Pass the hatchet counter-clockwise round the circle asking each person to hold it for a few moments: they can remain silent or say any appropriate words that come into their heads before passing it on to the next person."),
    SpellModel.init(categoryId: 1, spellId: 3, spellName: "Feuding Families", spellContent: "Ingredients:\n\nA pink taper candle\nA bowl of water\nSome rose essential oil or a crystal of rose quartz Tuberose, morning glory, violets or meadow sweet \n\nWhen everyone else is asleep, take the ingredients to your sacred space and consecrate them before lighting the candle. Spend some time focused on the flame, seeing it getting larger and larger and burning brighter and brighter, filling the house with peace and banishing all discordant vibrations. Don’t be tempted to rush this. Spend as long as it takes until the visualization is complete.\n\nTake the flowers and the water round the house, room by room, inside and out, dipping the flowers into the water and using them to sprinkle it around, seeing love and peace rain down with each droplet. Sprinkle a little extra water in rooms where arguments seem to break out most – usually the kitchen or bathroom! And as you go, very softly say aloud:\n\nWater gentle. Flower bright.\nRestore peace and love here tonight.\nMake my family a happy one.\nBy my will, this spell is done.\nAnd let it be done, that it harm no one.\n\nIt shouldn’t be too long until everyone is talking to each other again."),
    SpellModel.init(categoryId: 1, spellId: 4, spellName: "Stop Family Arguments", spellContent: "Ingredients:\n\nA hair from your own head and from the\nperson/s you are squabbling with Red thread\nA light blue taper candle\nPetals from a deep-red rose\n\nRub the hairs between your fingers to twist them together, and wind them round the red thread in the same way. Twine them clockwise three times round the candle, about a third of the way down, and put the candle in the centre of a pentagram made from the rose petals. When you feel the moment is right, light the candle and focus on the flame for a moment or two, visualizing how much better life will be when harmony has been restored and say:\n\nAmong those with whom I live my life,\nPlease send harmony to replace strife.\nAnd let it be done, that it harm no one"),
    /// `Blessings Spells`
    SpellModel.init(categoryId: 2, spellId: 5, spellName: "Give A Blessings", spellContent: "Ingredients:\n\nOne white candle\nBlessing oil (available from specialist shops)\nA bolline or burin\n\nCarve the name of the person to be blessed (in this example, you, the reader) on the candle and dress it with the oil. For the next seven days burn an equal part of the candle, snuffing it out after these words (or similar) have been spoken:\n\n*******\nMay nothing ever harm you.\nMay love be yours to give and take.\nMay nothing ever alarm you May wealth be yours to make.\nMay your health be good and your mind be strong.\nMay your friendships be the best.\nMay your heart be strong and your life be long.\nDear Reader, may you be blessed.\nAnd let it be done, that it harm no one."),
    /// `Business Spells`
    SpellModel.init(categoryId: 3, spellId: 6, spellName: "Business Prosperity", spellContent: "Ingredients:\n\nSome fresh basil leaves\nA bowl of spring water\nA crystal of citrine\nDried ears of corn\nSome grains of rice\nMint leaves\n\nBefore you perform the opening rituals, soak the basil leaves in the water for about an hour, stirring it clockwise occasionally. Now consecrate the herbal water and visualize your office or workplace. Starting in the east, walk round the circle, sprinkling the consecrated water as you go, and saying the following three times:\n\nMay business prosper,\nMay my dealings flow,\nMay my business be successful,\nMay my business grow.\n\nAfter the third time say, ‘And let it be done, that it harm no one.’\n\nCarry the mint leaves in your wallet, replacing them with fresh ones when you next feel it appropriate to do the spell."),
    /// `Career and Job Spells`
    SpellModel.init(categoryId: 4, spellId: 7, spellName: "Get Interviews", spellContent: "You will need:\nSome silver tinted leaves, e.g. silver birch\nYour career résumé, educational certificates\nThe ad describing the job you want\nOne white altar candle\nOne silver taper candle\n\nLight the white candle and, focusing on the flame, spend a minute or two meditating on the job you want. See yourself shaking hands with the interviewer and imagine yourself doing the job successfully. Ask your favourite deity or deities to smile on your endeavours before lighting the silver candle. Then, standing in front of the altar with your arms at full stretch above your head, say:\n\nThe job I want is in my ken.\nMake me first among all men,\nMay those who interview me see,\nThat the one they need is me.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 4, spellId: 8, spellName: "Make that Dream Job Yours", spellContent: "You will need:\n\nTwo brown candles\nOne green candle\nOne personal candle Incense associated with prosperity, such as ginger or cinnamon\nA similar essential oil\n\nAnoint all the candles with the oil, working towards yourself if you are casting the spell on your own behalf, away from you if you are casting the spell on someone else’s behalf. Then place one of the brown candles in the centre of your altar with the green candle on the right and the personal candle on the left. Light the personal candle, saying as you do so:\n\n\nPlease open the way\nPlease clear my/****’s sight,\nBring me/**** the chance,\nThat is mine/*****’s by right.\nAnd let it be done, that it harm no one.\n\n\nLight the green candle and say:\n\n\nGood luck be mine/*****’s, and victory\nWith your help will come my/*****’s way.\nAnd let it be done, that it harm no one.\n\n\nNow light the brown candle and say:\nOpportunities and rewards I see,\nAnd as I do, so must it be.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 4, spellId: 9, spellName: "Worth the Wait", spellContent: "Ingredients:\n\nOne large black candle\nA banishing essential oil, such as yarrow or one bought from a specialist shop\nA bolline or burin\nTwo pieces of parchment\nAn ink pen\nA green candle\nBergamot or another essential oil that draws money or success A yellow candle (or one in a colour associated with your favourite deity)\n\nInscribe on the black candle the things that are holding you back – nerves, lack of experience, whatever, and write the same things on one of the pieces of parchment. Dress the candle with the banishing oil and light it every night for nine nights, timing it so that on the ninth night the candle will burn out. Focus on the flame, visualizing the things you see as holding you back disappearing. On the ninth night, burn the parchment you wrote these things on and when the ashes are cool, take them outside and scatter them in the wind, watching the last of the reins on your ambitions vanish.\n\nNow focus on the job you want and what you would like it to yield for you. Inscribe these on the green candle and write them on the second piece of parchment, then anoint the candle with the drawing oil. For the next four nights, light the candle at the same time each night and see in the flame the things you want coming your way and how good life will S be when you have them. On the fourth night, burn the second piece of parchment and extinguish the candle with a snuffer or between finger and thumb. Put the candle stub and the ashes in a box and keep it somewhere safe.\n\nIf appropriate words come to mind at any time during the magic making, don’t let any inhibitions prevent you from saying them."),
    SpellModel.init(categoryId: 4, spellId: 10, spellName: "Getting the Right Job", spellContent: "Ingredients:\n\nTwo teaspoons of almond or any suitable carrier oil\nLemongrass pure essential oil\nA mixing bottle\nAn indigo tablecloth\nA crystal of amethyst\nThe Help Wanted column from the newspaper you read\nSchool and further education certificates\nOne white altar candle\nOne silver candle\nA bolline or burin\n\nDrizzle three drops of the lemongrass oil into the carrier oil and mix the two by rubbing the mixing bottle between the palms of your hands until you feel that it is charged with your ambition. Light the white candle and meditate quietly on the purpose of the spell. When you feel the time is right, inscribe the number ‘3’ onto the silver candle with the burin and then anoint it with the oil. Make sure you rub from the middle in as you are drawing something towards you. Now light the candle, focus on its flame and say:\n\n\nPlease carry to me the news,\nThat I will get an interview.\nThat I may be given the chance\nMy career prospects to enhance.\nAnd let it be done, that it harms no one."),
    SpellModel.init(categoryId: 4, spellId: 11, spellName: "Progressing your Career", spellContent: "Ingredients:\n\nTwo teaspoons of almond or any suitable carrier oil\nNeroli essential oil\nA mixing bottle\nAny suitable favourite herb\nAny suitable favourite essential oil\nA piece of sun stone\nOne white altar candle\nOne gold or yellow taper candle\nA bolline or burin\n\nAdd three drops of the neroli oil to the carrier oil and charge by rolling the mixing bottle between the palms of your hands and visualizing the oil being empowered with gratitude.\n\nLight the candle, stand in front of the altar and say:\n\n\nJob opportunities please come my/*****'s way,\nOn this very blessed day.\n\nChange my/****'s life and make it better,\nThanks to you, the true begetter.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 4, spellId: 12, spellName: "A Spell to Cast on the New Moon", spellContent: "Ingredients:\n\nTwo brown candles\nOne green candle\nOne astrologically compatible coloured candle\nCinnamon essential oil\nAn oil burner\nA favourite talisman of whoever the spell is directed to\n\nPosition one of the brown candles in the centre of the altar, the green one to its right and the personal candle to the left. Put the burner containing the essential oil in front of the brown candle and lay the second brown candle on its side in front of it. Put the talisman in front of the personal candle.\n\nLight the personal candle and as you focus on the flame, say:\n\n\nSpirit of fire, clear my/****’s sight,\nAnd bring me/**** chances mine/****’s by right.\nAnd let it be done, that it harm no one.\n\nNow light the green candle and focusing on the flame, say:\n\n\nNew horizons stretch out for me/****,\nMay fortune be mine/his/hers. And prosperity.\nAnd let it be done, that it harm no one.\nNew job, new responsibility.\nAs I will them, let them be.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 4, spellId: 13, spellName: "Make a Job opportunity Come Knocking at Your Door", spellContent: "Ingredients:\n\nA bowl of jasmine\nWriting paper\nDiamond or ruby jewellery\nScissors\nOne white altar candle\nOne silver taper candle\nNeroli essential oil\nA pen\nCardboard\nGold foil\nOne gold tapercandle\nA fireproof dish\n\nAfter decorating your altar, consecrate the paper, pen and any other items that have not been used before. Cut circular shapes out of the cardboard and cover them with gold foil to represent the sun and scatter them around the altar. Now write on the piece of paper, ‘We would like you to have...(whatever job opportunity is hoped for).’ Put the paper in the envelope and address it to the person the spell is being directed to, either yourself or a third party.\n\nLight the altar candle and sit for a minute or two thanking your deities for the gifts you have already been granted and for the successful magic you have already made.\n\nOpen the envelope, take out the letter, and light the gold and silver candles. Hold the envelope to the silver flame and when it has taken, drop it into the fireproof dish. As it burns see the opportunity you have asked for take wing and fly in the direction you wish. When the envelope has burned out, light the gold candle and use the flame to set the letter alight, and as it burns in the dish, see the news being joyfully received and the career being boosted.\n\nAllow the candles to burn through using the time to visualize the career having blossomed and the recipient enjoying its benefit."),
    /// `Courage Spells`
    SpellModel.init(categoryId: 5, spellId: 14, spellName: "Ask for Courage", spellContent: "Ingredients:\n\nOne white altar candle\nOne red taper candle\nSome sprigs of holly or honeysuckle\nAn essential oil burner\nLavender essential oil\nBlack pepper\n\nWhen the fumes of the lavender oil are filling the air, sprinkle the pepper onto the burner. Now light the white candle and kneel down, focusing on the flame while silently asking for the courage to face whatever challenges lie ahead. Visualize yourself triumphant in any situation and then light the red candle. Now stand to your full height in front of the altar and, with hands held high above your head, say aloud:\n\nStrength and courage may I possess,\nThat what I fear, I may face.\nIn winning through to the other side,\nOn to victory I will ride.\nAnd let it be done, that it harm no one."),
    /// `Forgiveness Spells`
    SpellModel.init(categoryId: 6, spellId: 15, spellName: "Seeking Forgiveness", spellContent: "Ingredients:\n\nAn apache teardrop crystal\nA bowl of daffodils\nA piece of angelica\nA piece of writing paper\nA pen\nA silver or platinumobject\nOne white altar candle\nOne violet taper candle\nA small ash twig\nA fireproof dish\n\nAfter you have lit the white candle and focused on the flame, ask of your deities that you will be granted forgiveness and the ability to forgive. Write on the paper what it is you need to be forgiven for or for which you need to forgive somebody else.\n\nNow light the violet candle and use its flame to set the paper alight. When it is burning, drop it in the fireproof dish, stand in front of the altar and say:\n\nTo the power I believe I now pray,\nThat hurts to me are now forgiven.\n‘Sorry’ is the word I’ll say.\nPeace be restored and peace be risen.\nAnd let it be done, that it harm no one."),
    /// `Friendship Spells`
    SpellModel.init(categoryId: 7, spellId: 16, spellName: "Restore Friendship", spellContent: "Ingredients:\n\nAn old scarf long enough to go right round the tree\n\nHolding the scarf in your hand you pass through the cleft in the tree nine times counter-clockwise saying:\n\nWhere there is pain,\nLet friendship now reign.\nAnd let it be done, that it harm no one.\n\nIf you cannot climb through the tree, simply walk around it.\n\nNow do the same again, nine times clockwise, saying:\n\nMay bitterness end,\nAnd ill feelings mend.\nAnd let it be done, that it harm no one.\n\nNow loop the scarf right round the tree and tie three knots to bind the ends together. As you tie the knots say:\n\nKnot one, sorrow end.\nKnot two, be us friend\nKnot three, heal the pain,\nLet love flow again.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 7, spellId: 17, spellName: "Friend Who Have Fallen Out", spellContent: "Ingredients:\n\nA photograph or something belonging to the other person\nA photograph of yourself\nA paper clip\nBasil essential oil\nSome nettles\nA crystal of garnet\n\nClip the two photographs together. Or if you are using something belonging to the other person, clip your photograph to it. Now say:\n\nLet friendship and harmony be restored.\nOn troubled waters, oil has poured.\nAnd let it be done, that it harm no one."),
    /// `Gossip Spells`
    SpellModel.init(categoryId: 8, spellId: 18, spellName: "Stop Tongues Wagging", spellContent: "Ingredients:\n\nA red taper candle\nA red pen\nA very small square of paper\nA snapdragon (antirrhinum) stem\nA thorn\nSome red ribbon\n\nFacing south, light the red candle, seeing in its flame the face or faces of the source of the gossip. Write their names on the paper with the red pen. If you are unsure of who it is, simply write, ‘whomever you may be’. Fold the paper into a tiny scroll.\n\nCarefully pluck the largest flower from the snapdragon and very gently open it out. Roll it round the scroll, repeating these words or ones similar, five times:\n\nLet your tongue speak goodness,\nLet your thoughts be kind,\nConsider your own faults,\nI know mine.\n\nUse the thorn to keep the scroll in place and as you pierce the flower, say:\n\nProtect me as their lips do part,\nWords not spoken from the heart.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 8, spellId: 19, spellName: "Spell for Smudgers", spellContent: "Ingredients:\n\nA Spell forSmudgers\nA smudge stick\nA feather or shell to waft the smoke\nLong-stemmed matches\n\nLight the smudge stick and blow on it gently until it has caught well and is smoking profusely. If it is a single room you are cleansing, move clockwise around it three times starting at the door and wafting the smudge stick in front of you. As you go say something along the lines of:\n\n\nGo negativity.\nGo all fears.\nGo all problems.\nGo all tears.\nAnd let it be done, that it harm no one. A Miscellany"),
    SpellModel.init(categoryId: 8, spellId: 20, spellName: "Return Unwanted Attention", spellContent: "Ingredients:\n\nVervain leaves\nA well-stoked fire\n\nConsecrate the wood or coal before lighting the fire. When it has taken, throw the vervain onto the flames, calling out the name of the person you want out of your life as loudly and with as much passion as you can muster. Follow the name with these words, which should also be said with passion:\n\nI want you not ever.\nI need you not ever.\nLeave my life now,\nAnd come back never.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 8, spellId: 21, spellName: "See a Rival on Their Way", spellContent: "Ingredients:\n\nA new, small glass bowl\nA cup of stagnant water\nTwo teaspoons of vinegar\nSome ground angelica Lime juice A wooden spoon On the night when the moon starts to wane take all the ingredients outside and mix them in the bowl with the wooden spoon. When everything is thoroughly mixed, hold your face close to the bowl and say something along the lines of:\n\nI’m the man/girl **** wants to love.\nWe go together hand in glove,\nAnd so I want you to know,\nThe time has come for you to go.\nAnd let it be done, that it harm no one."),
    /// `Gratitude Spells`
    SpellModel.init(categoryId: 9, spellId: 22, spellName: "A Spell to Say Thank You", spellContent: "Ingredients:\n\nAny silver items\nOne white altar candle\nOne silver taper candle\nA nosegay of white flowers\nA bowl of fruit\nA dish of coins\nA crystal of snow quartz or an opal\n\nLight the white candle and as it burns meditate on it. Give silent thanks for the gifts you have received and for which you are saying thank you. Now light the silver candle, rise to your full height and bringing your hands high above your head, say:\n\nBy the light of the sacred flame,\nthank you for the magic cast in your name.\nAnd let it be done, that it harm no one."),
    /// `Health Spells`
    SpellModel.init(categoryId: 10, spellId: 23, spellName: "Restore Good Health", spellContent: "Ingredients:\n\nSomething cast from gold\nA white altar candle\nA green taper candle\nA dish of daffodils or yellow roses\nA crystal of clear crystal quartz\n\nLight the white candle, focus on it for a few moments and visualize the person to whom the spell is being directed as being in perfect health and say:\n\n\nBody be healthy. Body be strong.\nSing out voice in happy song.\nPerfect health to ***** restore,\nAnd may it stay so evermore.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 10, spellId: 24, spellName: "Healing", spellContent: "Ingredients:\n\nA Spell forHealing Two teaspoons of almond oil (or any suitable carrier oil)\nSandalwood essential oil\nA bottle\nA crystal of quartz\nA sprig of lavender\nA white altarcandle\nA green taper candle (see above)\nA bolline or burin\n\nAdd three drops of sandalwood oil to the carrier oil and empower it by rolling the bottle between the palms of your hands. Light the white candle and meditate on how much better life will be for either you or whoever you are directing the spell to when their health improves.\n\nLight the candle and say:\n\n\nSure and quickly healing flow,\nPlease make ******’s illness go.\nPowers that be I request,\nYou let it be, and for the best.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 10, spellId: 25, spellName: "Healing Spell that Uses Knots", spellContent: "Ingredients:\n\nA piece of cord just over eight inches long\nSalt A tin\nPaper\nA fountain pen\nSealing wax or Sellotape\n\nMark the cord at six equal intervals so that you have seven equal lengths. Tie a knot at each mark, starting with the two central ones, then the ones at either end, finishing with the ones in between, saying each time you tie a knot:\n\n\nSickness, no one needs you to stay.\nIf you please, go away.\nBy these knots I say, ‘Depart!’\nAnd leave me/**** in better heart.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 10, spellId: 26, spellName: "Break Unhealthy Habits", spellContent: "Ingredients:\nA flowerpot\nPotting compost\nHyacinth bulbs or some sweet-smelling herbs\n\nFill the pot with the compost and plant your bulbs or herbs. As you do this, see yourself addiction-free or sticking to your diet, and looking much healthier as a result. Pat the compost nine times with your finger, saying:\n\n\nOh Powers that make these bulbs/herbs to grow,\nI ask that my addiction too shall go.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 10, spellId: 27, spellName: "Conquer Dependence", spellContent: "Ingredients:\n\nA crystal of amethyst\nAn orange taper candle\nA purple taper candle\nA red taper candle\nA glass of wine\n\nPut one candle at each point of an imaginary triangle large enough for you to sit within. Sit cross-legged facing the orange candle, the red one behind you to the left and the purple one behind you to the right. Put the wine between you and the orange candle, with the crystal alongside it. Before you light the candles, take several deep breaths through the nose, and hold them for a count of seven before breathing out through the mouth. As you inhale and exhale, visualize the crystal becoming empowered with your willpower. When you feel ready, light the candles, take the crystal in your hand and clasping it tightly, say:\n\nOrange candle, please restore my balance.\nPurple candle, please restore my inner harmony.\nRed candle please restore my courage,\nThat I may live my life, dependence-free.\nCrystal I know I need your power.\nGrant that it around me shower.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 10, spellId: 28, spellName: "A Kite Spell for Health", spellContent: "Ingredients:\n\nA kite (one with not too strong string is best!)\nSuitably coloured ribbons\nScraps of paper\nA pen (if you choose one appropriately coloured for the illness, so much the better)\nString\n\nTie the ribbons to the kite and write down your wish for improved health or recovery from a specific disease/condition on the scraps of paper and say:\nKnot I tie,\nKite I fly,\nCast my wishes,\nIn the sky.\nAnd let it be done, that it harm no one.\n\nWatch it go, shouting at the top of your voice:\n\nPowers that be,\nI ask you to see,\nThat I be free,\nFrom illness\nAnd let it be done, that it harm no one."),
    /// `House Blessing Spells`
    SpellModel.init(categoryId: 11, spellId: 29, spellName: "Bless a New House", spellContent: "Ingredients:\n\nSea salt\nA small bowl\nRose geranium essential oil\nAn aromatherapy burner\nA white candle Spring water\nA few grains of rice (organically grown if possible)\nA 15 cm (6 in) square of golden fabric\n\nConsecrate an area in which you can bless all the ingredients. Starting in the room at the top of the house (or the room immediately to the right of the front door in a flat), sprinkle a pinch of salt in each corner and on all corners of each window and door. As you sprinkle the salt say:\n\nPlease remove negative and unnecessary forces from this space,\nAnd make this room a special place.\nAnd let it be done, that it harm no one."),
    /// `Inspiration Spells`
    SpellModel.init(categoryId: 12, spellId: 30, spellName: "Self Inspire", spellContent: "Ingredients:\n\nTwo teaspoons of almond oil (or any suitable carrier oil)\nPeppermint essential oil\nA mixing bottle\nAn indigo candle\nA white candle\nPour the almond oil into the mixing bottle and add three drops of the peppermint oil. Light the white candle and meditate on the purpose of the spell for a minute or two. Now roll the bottle between hands held prayer-style and when you feel it has been charged with gratitude, return it to the altar. Inscribe the indigo candle with the number ‘1’ before anointing it with the charged oil. Return it to its holder and light it. Hold your hands towards the flame and say:\nI ask of you, Oh Powers that be,\nTo send inspiration down to me.\nTo fill my mind with ideas clear,\nAnd remove from me all trace of fear.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 12, spellId: 31, spellName: "Inspire Others", spellContent: "Ingredients:\n\nA white altar candle\nAn indigo altar cloth\nA book that you find inspirational - for the altar Items made of aluminium (if none are available cover something with aluminium foil) - for the altar\nA vase of anemones - for the altar\nA sprig of sage - for the altar\nA hazel twig - for the altar\nAn indigo taper candle\nAn amethyst crystal Light the white candle and pick up the crystal. Squeeze it tightly and visualize motivation slowly developing inside you and flowing into the crystal. Now light the indigo candle and standing to your full height, with your hands above your head, say aloud:\n\nInspiration light my life,\nMotivate and guide my way.\nPowers that guide me,\nHear me pray.\nAnd let it be done, that it harm no one."),
    /// `Kindness Spells`
    SpellModel.init(categoryId: 13, spellId: 32, spellName: "Asking for Kindness", spellContent: "Ingredients:\nA small strip of paper\nA pen\nA small, clean jar with a lid (an old baby food jar would be ideal)\nRunny honey\nOne pink candle (representing affection and friendship)\n\nWrite the name of the person to whom the spell is being directed on the paper and put this in the jar. Use a honey dripper to drizzle honey into the jar (if you try to pour it in, honey has a tendency to go anywhere but where you want it to). As the jar fills, visualize the other person being kind to you as you would like him or her to be. When the jar is full, put the lid on and seal it with the molten wax from the pink candle.\n\nKeep the jar on your altar or in a place where it will not be touched by anyone else. The energy of thespell is recharged every day by putting the jar in a sunny spot. After six months bury the jar and recast the spell if you need to, but by then, the other person should have been especially kind to you. (If you want people in general to display kindness to you, then simply write ‘All Mankind’ on the paper before putting it in the jar.)"),
    /// `Loneliness Spells`
    SpellModel.init(categoryId: 14, spellId: 33, spellName: "For Those Who Are Lonely", spellContent: "Ingredients:\n\nA piece of scrap paper\nA piece of parchment\nA pen\nAn orange candle\nAn empty hurricane lamp\nA bolline or burin\nA jar\nSalt\n\nTake some time to write down what your personality traits are, your likes and dislikes and a few sentences that summarize your character. Now précis what you have written in as few words as possible, but retaining their essence, and write these on the parchment. The reason for keeping the words to a minimum is that now you inscribe them onto the candle.\n\nFill the jar one third of the way up with salt and bury the rolled up piece of parchment in it before sealing the jar and putting it in as safe a place as possible near your bed.\n\nBefore you go to bed, put the inscribed candle into the hurricane lamp and light it. Make sure that it is in a safe place, and that if you have a cat or dog, they are kept out of the bedroom as accidents can happen. Say the following words:\n\nHelp me, please, to make new friends,\nSo my loneliness will be at an end.\nAnd let it be done, that it harm no one."),
    /// `Lost Items Spells`
    SpellModel.init(categoryId: 15, spellId: 34, spellName: "Recover Something that has Been Lost", spellContent: "Ingredients:\n\nHoneysuckle essential oil\nA piece of new writing paper\nA new pen\n\nWrite whatever it is you have mislaid on the paper and lay it on your altar. Rub a drop or two of the honeysuckle oil on your temples, forehead and hands. Now move to the north of your circle and sitting facing south, the palms of your hands facing upwards, visualize yourself sitting on top of a mountain, able to see far in any direction.\n\nWith this picture firmly in mind, say:\n\n\nSafe and sure as I can be\nMay my ***** return to me.\nAnd let it be done, that it harm no one."),
    /// `Love Spells`
    SpellModel.init(categoryId: 16, spellId: 35, spellName: "Evoke a Romantic Response", spellContent: "Ingredients:\nA wine glass\nA plain gold ring\n80 cm of redribbon\nA crystal of rose quartz\nA bowl of red flowers\nA picture of the person you wish to attract, if available\n\nStand the wine glass on your altar. Thread the ribbon through the ring to make a pendulum and, holding the ribbon between your thumb and forefinger, let the ring hang in the rim of the glass, without letting it touch the sides.\n\nSay aloud your name and the name of the person you are attracted to. Pause for a moment then repeat both names again and then once more. Look at the picture (if you don’t have one, bring one into your mind’s eye) and spell their name out loud. As you say each letter, let the ring tap against the glass."),
    SpellModel.init(categoryId: 16, spellId: 36, spellName: "Win Affections", spellContent: "Ingredients:\n\nAn onion\nA new flowerpot\nPotting compost\nA bolline or burin (see pages 36-37)\nJasmine essential oil\nPatience\n\nScratch the name of the person you are in love with on the base of the onion with the bolline or burin and plant it in the flowerpot. Focus on the flowerpot for a moment or two, then say:\n\nPlant take root and grow shoots.\nShoots grow into leaves.\nMay a flower bloom among them.\nAnd as the flower blooms,\nMay *******’s love for me\nTake root, bloom and flower.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 16, spellId: 37, spellName: "Make a Love Grow", spellContent: "Ingredients:\n\nA packet of seeds\nA new flowerpot\nPotting compost\nA small copper coin\n\nBefore you open your circle take the coin outside and hold it up to the moon, focusing your mind on the one whose thoughts you are trying to direct towards you.\n\nNow go to your sacred space and, the opening rituals completed, bury the coin in the flowerpot. Sprinkle the seeds on top to form the initials of the other person’s first and last name. As the seeds germinate and start to shoot, so love should take root and blossom in your life."),
    SpellModel.init(categoryId: 16, spellId: 38, spellName: "Revive Passion", spellContent: "Ingredients:\n\nLots of laurel leaves\nA fire in embers (see above)\n\nGaze at the embers, a picture of your love in your mind’s eye, for a moment or two before throwing some of the laurel leaves onto the embers. As they smoulder say:\n\n\nSacred leaves glow in the fire\nWarm the heart of my true love’s desire.\n\n\nWhen the leaves have burned away, repeat the ritual twice, adding, ‘And let it be done, that it harm no one,’ the last time you say the words."),
    SpellModel.init(categoryId: 16, spellId: 39, spellName: "Have a Love Returned", spellContent: "Ingredients:\n\nA pink candle (representing the female)\nA blue candle (representing the male)\nA gold candle\nA horseshoe\nA key\nTwo roses (preferably, but not necessarily, red)\nAn article of the other person’s clothing\nA large bowl\nPot pourri\n\nFemale spell casters should light the pink candle first then the blue one. Men should light the blue one first then the pink. When these two candles have been lit, light the gold one and put it between the other two. Now place a rose alongside the two outer candles and put the horseshoe at the far side of one of the roses and the key at the far side of theother one.\n\nAs the candles burn, focus on your heart’s desire until the flames flicker and die or you have to bring the ritual to an end, in which case extinguish the flames in the usual way."),
    SpellModel.init(categoryId: 16, spellId: 40, spellName: "No One Partiular in Mind", spellContent: "Ingredients:\nRose petals from a living, wild rose\n\nAs you are plucking the petals, visualize someone who has all the qualities you think are necessary in the ideal partner – humor, generosity, compassion, whatever. Take the petals to a stream or river, hold them in cupped hands and, again visualizing the qualities you are looking for, let them drop into the flowing water, saying:\n\n\nAs this bloom is taken downstream\nMay I find the love of which I dream.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 16, spellId: 41, spellName: "Find New Love", spellContent: "Ingredients:\n\nA salt shaker\nA pepper shaker\nThree feet of pink ribbon\n\nAs you consecrate the ingredients, think of one of the spices as masculine and the other as feminine. Then tie the female object to one end of the ribbon and the male one to the other end. As you are doing this say:\n\n\nRibbon of love, as I bind thee,\nPlease let true love find me.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 16, spellId: 42, spellName: "Find Our a Lover's Intials", spellContent: "Ingredients:\n\nAn apple\nA bolline\n\nInvoke the four elements in a quicker way than usual by standing before your altar and saying:\n\n\nFire, Earth, Air, Water\nSpirits of the elements be with me.\n\n\nThat done, peel the apple, keeping the peel in one piece. Now holding the peel in your right hand say:\n\n\nSpirits of love. Spirits of Good\nOn you now I beg to intrude,\nWith this token to discover\nThe initial of my one true lover.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 16, spellId: 43, spellName: "Love Within the Month", spellContent: "Ingredients:\n\nA heart-shaped rose petal (if this is not available, cut a heart shape out of a piece of red paper)\nA clean sheet of white paper\nA new pen\nA pink candle\nA new envelope\n\nOn the day when a new moon is due to appear in the sky, write the following on a fresh sheet of paper with the new pen:\n\n\nAs this heart glows in candlelight\nI draw my love to me tonight.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 16, spellId: 44, spellName: "True Love", spellContent: "Ingredients:\n\nA piece of rose quartz, jade, aventurine or moonstone\nChamomile, sorrel or bay\nGardenias, tansies or roses bound as a posy\nSunflower or a suitable carrier oil\nOne of these essential oils: rose absolute/bulgar/maroc/ patchouli/jasmine/ylang-ylang/geranium\nAny small item that holds romantic associations for you\nOne white altar candle\nTwo pink taper candles\nYour bolline or burin\n\n\nAdd one drop of your chosen essential oil to the carrier oil and place it on the altar with the other materials you are going to use.\n\n\nNow light both pink candles, saying:\n\n\nLove to me please bring,\nBy the power of love so true,\nFill my heart and make it sing,\nRejoice and help me love anew.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 16, spellId: 45, spellName: "For the Lovelorn", spellContent: "Ingredients:\n\nA bottle of rose water\nNine feet of white cord\nFour green candles\nOne pink candle\nCharcoal and a small charcoal burner\nTwelve or so freshly plucked rose petals and some rose essential oil\nA cinnamon stick A gold pen\nA glass bowl filled with fresh spring water\nA bowl of earth\n\nLight one of the green candles at each of the four major compass points of your circle and invoke the winds, facing each direction in turn, with these timeless words:\n\n\nHail to thee East Wind\nHail to thee South Wind\nHail to thee West Wind\nHail to thee North Wind\nI call for love\nAnd make this offering to you."),
    SpellModel.init(categoryId: 16, spellId: 46, spellName: "Find Love for First Time", spellContent: "Ingredients:\n\nA fresh, fragrant red rose\nSeveral red candles\n\nIn the morning, take the rose outside and say:\n\n\nRed rose, true love’s flower,\nPlease lend me your power,\nTo give someone my heart,\nAnd never shall we part.\nAnd let it be done, that it harm no one.\n\n\nPut the rose back in its place on the altar and light the two candles. Spend a minute or two focused on the flames, visualizing love warming the heart of the one you desire. Repeat the ritual each night until the rose fades, using the flames of the dying candles to light new ones."),
    SpellModel.init(categoryId: 16, spellId: 47, spellName: "When Love is Shaky", spellContent: "Ingredients:\n\nA fresh apple\nA clean sheet of white writing paper\nAn unused pen\nA knife\nTwo pins\n\nSlice the apple in half without cutting through the seeds. If you are casting the spell for yourself, write your own name and the name of the other person on the paper. If you are casting it on behalf of another couple, write their names on the paper. In either case, make sure that the names take up less than the width of the apple.\n\nNow cut out the names and put the paper bearing them between the two halves of the apple. Bring them together and visualize harmonious relations restored."),
    SpellModel.init(categoryId: 16, spellId: 48, spellName: "Keep Lover Faithful", spellContent: "Ingredients:\n\nTwo nutmegs\nA pair of your underwear\nA pair of your partner’s underwear\nSome wide red ribbon\nA large envelope (white if possible)\nA bolline or burin\n\nInscribe your name on one of the nutmegs and your partner’s name on the other. That done, bind them together with the ribbon, saying these, or similar words as you do so:\n\n\nAs I bind these fruits of tree\nLover, never stray from me.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 16, spellId: 49, spellName: "Fill a Lonely Gap", spellContent: "Ingredients:\n\nThree chalices\nCinnamon essential oil (or a favourite love drawing oil) or some vanilla extract\nAn orange taper candle\nWater\n\nLight the candle and charge the oil, holding the bottle it is in up to the candlelight and rolling it between the palms of you hands, visualizing as you do so how complete your life will be when love enters it. Half fill two of the chalices with water and put them on your altar with the empty one between them. The partially filled chalices represent you and a new love, both incomplete until you are drawn together and become one. The empty one stands for what you can achieve together.\n\nDrizzle three drops of the essential oil or extract into the empty chalice, using some suitable words to explain the purpose of the spell. If you have a particular person in mind, remember to say that you acknowledge his or her free will and that you are not trying to interfere with it.\n\nNow with a picture of yourself and the other person enjoying each other’s company in the special way that lovers do, take one of the half- filled chalices and then the other, adding a little water from each to the oil/extract-charged one."),
    SpellModel.init(categoryId: 16, spellId: 50, spellName: "A Spell to Mend a Lovers' Quarrel", spellContent: "Ingredients:\n\nTwo silver pins\nA red candle\nAny red crystal\nSome red flowers\nA red altar cloth\n\nSpread the cloth on your altar. Put the candle in the middle and arrange the flowers and crystal around it. Once the opening rituals have been completed, pierce the candle with the two silver pins, one higher than the other, and light it. Focus your thoughts on your lover and when the flame reaches the first pin say aloud:\n\n\nTo the Spirit of Love I now attend,\nDon’t let our love come to an end.\nAnd let it be done, that it harm no one.\n\n\nRepeat this until the flame reaches the second pin, then say:\n\n\nMay ***** and I be one again,\nBy the warmth of this candle flame.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 16, spellId: 51, spellName: "Ending Love", spellContent: "Ingredients:\nA small square of paper\nA fountain pen filled with black ink (a black ballpoint will do, but a fountain pen is best)\nA white taper candle\nA fireproof dish\n\nWrite the name of the person you don’t want to be involved with on the paper. Once the ink is dry, light the candle and hold paper in its flame until it starts to burn. Hold the paper in front of you, trying to see the fumes curling round the person and wafting him or her away from you. When you can no longer hold the paper, drop it into the fireproof dish, still seeing the smoke carry him or her away, and say:\n\n\nWind of North, Wind of East,\nWind of South, Wind of West,\nTake these feelings to where they best\nBe appreciated.\nPlease let ***** see,\nThat his/her love is not for me.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 16, spellId: 52, spellName: "Make Someone Accept the Invitable", spellContent: "Ingredients:\n\nPumpkin seeds\nA trowel\nA sketch of your ex smiling at a new love\n\nTake the pumpkin seeds outside to a place where you will be unseen and undisturbed. Sit on the ground and dig a small hole in front of you. Breathe in deeply through the nose, hold the breath for a moment or two more than you would normally, and then breathe out though the mouth. Do this for a minute or two and as you do so, visualize your old love standing in front of you."),
    SpellModel.init(categoryId: 16, spellId: 53, spellName: "Love that is Slowing Dying", spellContent: "Ingredients:\n\nTwo silver-coloured heart-shaped lockets\nA length of white cord\nA length of pink cord\nA square of dark silk or cotton\nA photograph of you and the other person\nA white candle\n\nThread the lockets onto the white cord and tie the ends with a double knot. As you tie this, say:\n\n\nThis knot bound our hearts\nBut now has come the time to part.\nAnd let it be done, that it harm no one.\n\n\nUntie the knot, slowly, saying:\n\n\nThe ties that link us may have faded\nBut let our affection remain unjaded.\nAnd let it be done, that it harm no one.\n\n\nVery gently slide one of the lockets off the cord, saying as you do:\n\n\nI release you, for our love’s at an end,\nBut please forever be my friend.\nAnd let it be done, that it harm no one.\n\n\nThread the locket onto the pink cord and say:\n\n\nNow you are one, go in peace.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 16, spellId: 54, spellName: "Mend a Broken Heart", spellContent: "Ingredients:\n\nA teabag of strawberry tea\nA willow wand\nSea salt\nTwo pink candles\nA mirror\nA pink drawstring bag\nA crystal of quartz\nA copper coin\nA crystal bowl that has some sentimental value to you\nOne teaspoon of orris root powder\nOne teaspoon of dried jasmine\nOne teaspoon of yarrow\nA small handful of strawberry leaves\nTen drops of apple blossom essential oil\nTen drops of strawberry essential oil\n\nPlace one of the pink candles at the end of a bath and start to fill it with warm water. With the water running, prepare a cup of strawberry tea. When the bath is ready, light the candle and soak in the warm water until you feel relaxed enough to weave the spell. As you dry off, sip the strawberry tea and then dab the strawberry oil around your face.\n\nMake your way to your altar and cast a circle with the willow wand. Now light the second pink candle and put the other ingredients into the bowl. Stir them thoroughly, saying as you do:\n\n\nMother Earth I ask you for nurture andprotection.\nGive me the confidence to use the strengths I have.\nAnd let it be done, that it harm no one.\n\n\nWhen everything is thoroughly mixed, look at your reflection in the mirror and say:\n\n\nMother Earth, help me to be the person I know I am,\nAnd let me overcome my difficulty.\nAnd let it be done, that it harm no one."),
    /// `Luck Spells`
    SpellModel.init(categoryId: 17, spellId: 55, spellName: "Ask for Luck", spellContent: "Ingredients:\n\nOne white altar candle\nOne blue taper candle\nSeveral coins\nA sprig of white heather\nA sprig of clover\nA piece of gold or silver jewellery\nAmber or citrine crystals\nA piece of paper\nA pencil or pen\nA fireproof dish\n\nWrite the number down on the paper and place it on the altar. That done, kneel in front of it, light the white candle and meditate on your heart’s desire, visualizing your wish coming true. Light the blue candle and use its flame to set fire to the paper with your birth number written on it. Put this in the fireproof dish and as it burns, softly say these words:\n\nGuardians of this space I pray,\nGood luck be with me every day.\nPray bring to me some good news,\nAnd change my fortune that I do not lose.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 17, spellId: 56, spellName: "Ask for Whatever you Desire", spellContent: "Ingredients:\n\nA shell\nWatercolour paint of a colour appropriate to the reason for the spell\nA paintbrush\n\nNext time you visit a beach, look for a shell sitting in the shallow water. Take it home and dry it thoroughly. On a clear moonlit night at a time when the tide is about to go out, paint the desire of the spell on the outer part of the shell and take it to the beach. (The one you found it on is best but if that’s not practical take it to a convenient beach that lies in the same direction as the original one.) Place the shell pearly side down, written side up, where the waves will soon lap over it and draw a triangle round it. As the sea begins to wash over the shell, say:\n\n\nPowers of Earth, Moon and Sea,\nLend your power, please, to me.\nForces which the tide do make,\nAsk the waves, my spell to take.\nAnd let it be done, that it harm no one."),
    /// `Miscellaneous Spells`
    SpellModel.init(categoryId: 18, spellId: 57, spellName: "Reflecting the Moon's Power", spellContent: "Ingredients:\n\nA drill\nA gold-coloured coin\nAn eight-sided mirror\nOn a night when the moon is full, drill a hole in the coin and position the mirror so that you catch Her image on it. Hold the coin up so that the moon’s light shines through the hole, watching the gold rays cast by the coin merge with the silver rays of the moon. Focus on this and say:\nLady Moon, I ask this hour,\nFor money on me to shower,\nI ask for silver and for gold,\nBefore the moon grows old.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 18, spellId: 58, spellName: "A Spell that has Worked for Many", spellContent: "Ingredients:\n\nA very fragrant, fresh red rose\nTwo red candles\n\nAt sunrise take the rose outside, breathe in its sweet perfume and then hold it in front of you. Focus on it for a moment or two, then say:\n\n\nFlower of love, please let it be,\nThat true love is coming to me.\nAnd let it be done, that it harm no one.\n\nGo indoors and lay the rose between the candles and light them. Focus on the flame and see true love burning in the heart of the one you want to attract. Or, if you have no one special in mind, bring to mind someone with features and a nature you find attractive."),
    SpellModel.init(categoryId: 18, spellId: 59, spellName: "A Spell for Those Who Change Their Minds", spellContent: "Ingredients:\n\nA red candle\nA handful of dried beans\nA small, heat-resistant bowl\n\nClasp the beans in your hand and see them being filled with those feelings. Now put them in the bowl and move it clockwise above the flame (taking care not to burn yourself) seeing the beans as the catalyst that will bring you and your lover back together. As you do this, say these or similar words:\n\n\nLove that was, please be recovered.\nLet us be what we were to one another.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 18, spellId: 60, spellName: "A Colourful Spell that Take a Week to Cast", spellContent: "Ingredients:\n\nOne violet votive candle\nOne indigo votive candle\nOne blue votive candle\nOne green votive candle\nOne yellow votive candle\nOne orange votive candle\nOne red votive candle\nSeven candle holders\n\nArrange the candles in their holders on your altar, the violet one to the left, the red to the right with the others in between according to their place in the rainbow.\n\nOn a suitable Monday, the day of the moon, light the violet candle and say either these words or something similar:\n\n\nThrough violet haze my love I call,\nWhen moonlit rays upon him/her fall\n And by moon’s power help him/her see,\nOur love is seen and meant to be.\nAnd let it be done, that it harm no one.\n\n\nOn Tuesday, with its associations with Mars, light the indigo and say:\n\n\nIndigo, shade of twilight deep,\nMay my lover enjoy deep sleep.\nMars, in his/her dreams please let him/her see,\nThat he/she and I will soon be we.\nAnd let it be done, that it harm no one.\n\n\nOn Mercury’s day, Wednesday, repeat the ritual, saying as you light the blue candle:\n\n\nCandle blue please tell my love,\nWe go together hand in glove.\nMercury take a message clear,\nTo my true love – far or near.\nAnd let it be done, that it harm no one.\n\n\nOn Thursday light the green candle and say:\n\n\nCandle green please burn strong,\nAnd tell my love it won’t be long,\n’Til Jupiter says we’ll be together,\nNot for now, but together forever.And let it be done, that it harm no one.\n\n\nVenus, most associated with love, is called upon on Friday when the yellow candle is lit, with these words or some similar:\n\n\nCandle yellow, may your flame,\nMake my lover hear my name.\nVenus, please lend your power\nAnd on us may your blessings shower.\nAnd let it be done, that it harm no one.\n\n\nSaturday is the day to light the orange candle and to call on Saturn with these words:\n\n\nCandle orange, light the way,\nAnd make my lover hear me say,\nThat Saturn smiles from on high,\nAnd by my side my love will lie.\nAnd let it be done, that it harm no one.\n\n\nAnd on the Sunday, when the moon is full call upon the sun to bless your love:\n\n\nCandle red and sun above,\nKindle passion in my love.\nLet him/her know not any fear.\nThe time is right. The day is here.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 18, spellId: 61, spellName: "Small Beginnings", spellContent: "Ingredients:\n\nA piece of heart-shaped jewellery\nSome items made of copper or brass\nA piece of rose quartz\nTwo red roses\nAn apple\nOne or two photographs of happy couples\nOne white altar candle\nOne pink altar candle\nOil of ylang-ylang or patchouli\nA small flowerpot filled with potting compost\nYour knife\nA small glass of water\n\nDecorate your altar with the heart-shaped jewellery, the copper or brass items, the quartz and the red roses before laying the photographs between the white and the pink altar candles.\n\nSlowly and softly say:\n\nVenus shining in the night,\nBless my heart with love and light.\nLoved in truth I wish to be.\nListen to my prayer, my plea.\nMay I love and be loved in turn,\nAs brightly as the candles burn.\nIf I am loved help me see it.\nAnd harm no one. So be it.\nAs the seeds I have planted begin to grow.\nMay the love that I have begin to show.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 18, spellId: 62, spellName: "A Simple Spell", spellContent: "Ingredients:\n\nTwo leaves that can be drawn on\nGreen thread\nA needle\nSeven pennies\n\nTake the leaves to a tree that you are fond of, one with a natural crevice within which you can hide them. Making sure that they will not blow away, gently push the leaves into the crevice, saying as you do so:\n\nEarth, Water, Air and Fire,\nBring me *****’s true love as I desire.\nAnd let it be done, that it harm no one.\n\nNow bury the coins around the base of the tree and trust to the elements to make your magic work."),
    SpellModel.init(categoryId: 18, spellId: 63, spellName: "A Spell that Uses Seaweed", spellContent: "Ingredients:\n\nTwo oyster or mussel shells\nA pearl or a mother-of-pearl button\nSeaweed\nGreen twine\nA stick\n\nPut the pearl inside the shells, holding them open side to open side and cover them with seaweed. Bind the seaweed parcel together with the twine. Draw a circle in the sand with the stick, just above the tide line. Put the shells into the circle and when it is covered by an incoming wave, say:\n\n\nI return what was yours, Great Sea,\nPlease restore my prosperity.\nAnd let it be done, that it harm no one."),
    /// `Peace Spells`
    SpellModel.init(categoryId: 19, spellId: 64, spellName: "Promote Peace", spellContent: "Ingredients:\n\nOne white altar candle\nOne white taper candle\nA piece of jewellery cast from white gold\nA vase of lilies\nA crystal of rhodochrosite\nA large shell\nA small silver coin\nA picture of a dove\nA dish of chamomile\nA sprig of olive\n\nLight the white altar candle before kneeling in front of the altar holding the crystal in your hand. Focus your thoughts on it, trying to see a world where peace reigns. Let that peace flood through your body and say a silent prayer to the One in whose name you do magic.\n\nLight the second candle, focus on the picture of the dove and with hands held high say:\n\nTake to the air, Peaceful Dove,\nBanish hatred and spread love.\nFill minds of men with dreams of peace,\nAnd banishing war’s dreadful lease.\nAnd let it be done, that it harm no one."),
    /// `Pet Spells`
    SpellModel.init(categoryId: 20, spellId: 65, spellName: "Cat Lover Spell", spellContent: "Ingredients:\n\nTwo teaspoons of carrier oil\nThree drops of sandalwood essential oil\nA mixing bottle\nA picture or an ornament of a black cat\nCitrine or amber crystals\nOne white altar candle\nOne blue taper candle\nA bolline or burin\n\nPut the carrier oil in the mixing bottle and add the sandalwood oil. With your hands in prayer position, roll the bottle between the palms, visualizing good luck mixing into the blend.\n\nWhen you think the oil is fully charged with good fortune, put the bottle on your altar and spend a minute or two breathing deeply in and out. As you inhale, see white light enter your body and enshroud all negative energy. When you exhale, see this energy leave your body.\n\nWhen you feel fully relaxed, light the white candle and, focusing on its flame, see yourself as you will be when good luck comes to you.\n\nFocusing on making your wishes come true, hold the candle in the air above the image of the black cat, rolling the candle backwards and forwards between the palms of your hands. As you do so, repeat:\n\n\nCandle’s power and lucky cat,\nPlease change my luck, so that\nI achieve my heart’s desire,\nPowered by this magic fire.\nAnd let it be done, that it harm no one.\n\n\nAllow the candle to burn down or, if you have to, extinguish it with a candle snuffer or between finger and thumb."),
    SpellModel.init(categoryId: 20, spellId: 66, spellName: "When a Pet Dies", spellContent: "Ingredients:\n\nThree small brown taper candles\nRosemary essential oil\nSomething that reminds you of your pet – a lead perhaps, or a collar\n\nAnoint the candles with the oil before lighting them and focusing on the three flickering flames, conjuring up in your mind’s eye some of the happy memories that you have of your dead pet. Now, holding the memento in both hands, say aloud some words of thanks for the companionship and friendship it brought into your life before saying that now is the time to say a final farewell. See the candle flames grow as you say ‘Goodbye!’ Don’t snuff out the candles (that’s why they should be small). Rather, focus on the flames getting smaller and smaller, seeing your grief diminish with them. And when they die, know that your grief has died with them.\n\n\nFinish the ritual by saying:\nBe at peace,\nAnd blessed be.\nAnd let it be done, that it harm no one."),
    /// `Problem Solving Spells`
    SpellModel.init(categoryId: 21, spellId: 67, spellName: "Solve Problems", spellContent: "On a suitable day of the week, decorate your altar with things appropriate to your problem. For example, if you have a problem in the office, green would be a suitable theme and Friday a good day on which to work; some birch leaves or twigs (if you are planning a new beginning), some nasturtium (if you have been struggling, no matter how hard you have been working) and a crystal of tourmaline (the magic properties of which include friendship, prosperity, business and protection) will all strengthen the magic. And don’t forget to burn a suitable essential oil in an oil burner and to lay your favourite charm, talismans and the like on the altar.\n\nWhen everything is in position and you are ready to make your magic, simply say:\n\n\nPowers I believe in be with me.\nPowers I believe in talk to me.\nPowers I believe in help me see,\nThe answers to my problem.\nAnd let it be done, that it harm no one."),
    /// `Prosperity Spells`
    SpellModel.init(categoryId: 22, spellId: 68, spellName: "Attract Cash", spellContent: "Ingredients:\n\nA square of green cloth\nAllspice\nBorage\nLavender\nSaffron (which is expensive so use it sparingly)\nThree silver coins (if you have old silver threepenny pieces commonly put in Christmas puddings, so much the better)\nGold thread\nSilver thread\n\nBreathe on each of the silver coins in turn, saying something along the lines of:\n\n\nSpirit of Air, to you I pray,\nSend some money down my way.\nAnd let it be done, that it harm no one.\n\n\nNow put the coins and the spices in the bag. Tie four knots in the gold thread and four in the silver and use the knotted threads to tie the bag. Put the bag in a safe place – preferably a cool, dark one – and leave it there for eight days."),
    SpellModel.init(categoryId: 22, spellId: 69, spellName: "Make you Think About Money", spellContent: "Ingredients:\n\nA small bowl\nSeven coins\nA green taper candle\n\nPut everything on your altar along with lucky charms and talismans whose power strengthens your magic. And if you decorate the altar with a green cloth and some glossy leaves, all the better.\n\nOnce a day, drop one of the coins into the dish and on the seventh day, pick up the candle and, thinking about the opportunities having more money would create for you, visualize prosperity flowing into it. When you feel the time is right, put the candle in the middle of the altar and place one of the coins in front of it, saying:\n\n\nMay more money flow my way,\nNow and every other day.\nAnd let it be done, that it harm no one.\n\n\nAs the candle burns, focus on its flame and think again about your attitude to money and how it could be changed to make you a financially more responsible person."),
    SpellModel.init(categoryId: 22, spellId: 70, spellName: "Make a Money Bottle", spellContent: "Ingredients:\n\nFive pennies\nFive nickels\nFive dimes\nFive quarters\nFive cloves\nFive kernels of dried corn\nFive cinnamon sticks\nFive teaspoons of dried flour\nFive sesame seeds\nFive pecan nuts\nFive allspice\nFive grains of rice\nOne tall, thin glass bottle\n\nPut all the ingredients in the bottle. (As ‘5’ is associated with the colour turquoise, a bottle of that colour would add potency to the spell.) Ensure that the top is secure before giving the bottle a good shake for five minutes and saying such words as:\n\n\nCopper gleam. Silver shine.\nI ask you please to make wealth mine.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 22, spellId: 71, spellName: "Banish Poverty", spellContent: "Ingredients:\n\nA small bowl\nSalt\nSugar\nRice\nAn open safety pin\n\nFill the bowl with equal amounts of sugar, salt and rice. Put the open safety pin in the middle of the bowl. As you do so use your own words to ask the elements or the deities you believe in to ensure that no matter how long you live you will always have food in your stomach, money in your pocket and a roof over your head."),
    SpellModel.init(categoryId: 22, spellId: 72, spellName: "Bring Welth", spellContent: "Ingredients:\n\nOne or two gold or silver objects\nOne yellow taper candle\nOne white altar candle\nA small piece of coal\nA dish of salt\nA dish of silver coins\nJewellery inlaid with diamonds, jade or rubies\nYour purse or wallet\nA piece of paper and pencil\n\nLight the white candle then kneel in front of the altar and meditate on your current financial position. No matter how bad it is, see yourself putting money into your bank account, and paying off all your creditors one by one.\n\nStand to your full height and with arms outstretched above your head say:\n\n\nCoins that sparkle in the sun,\nCome to me when work is done.\nMake me richer so I may see,\nWealth aplenty come to me.\nAnd let it be done, that it harm no one."),
    SpellModel.init(categoryId: 22, spellId: 73, spellName: "Ask for Prosperity", spellContent: "Ingredients:\n\nTwo teaspoons of carrier oil\nRose essential oil\nA small bottle\nAny ornament that is precious to you\nAny crystal that has the reputation of bringing wealth, such as ruby or tiger’s eye\nA piece of jewellery An item of gold or silver\nOne white altar candle\nOne gold taper candle\nA bolline or burin\n\nPour the carrier oil into the bottle. Add three drops of rose essential oil and holding the bottle between the palms of the hands, roll it backwards and forwards until the oils are well mixed. As you do this, visualize the oil being blessed with the power of good fortune.\n\nFocus your attention and say:\n\n\nAs the flowers do bloom in spring,\nGods and elements to me wealth bring.\nBy your powers, banish strife,\nAnd bring enrichment to my life.\nAnd let it be done, that it harm no one."),
    /// `Protection Spells`
    SpellModel.init(categoryId: 23, spellId: 74, spellName: "When You Feel Threatened", spellContent: "Ingredients:\n\nA clear crystal of quartz or any favourite one that is full of clear light\n\nPlace the crystal on a table where it will catch the sunshine. Sit at the table and breathe in deeply through the nose. Hold the breath for a moment or two before exhaling through the mouth. Repeat this several times, absorbing the light cast by the crystal as you inhale and exhaling any negative feelings, doubts and darkness.\n\nAfter a minute or two, stand and begin visualizing a ring of crystal rising around you, from your feet upwards, getting higher and higher with each breath you take.\n\nStill breathing deeply, feel the crystal form a floor beneath your feet. Stretch your arms and feel your fingers touch the sides. Look upwards and see the dome or pyramid point. If you can, see yourself from outside the protective crystal in which you have surrounded yourself and say:\n\n\nWithin this crystal, I am safe from negative thought,\nAnd will be so, whenever I return to it.\nAnd let it be done, that it harm no one.\n\n\nWhen you feel it is right to do so, return to normal breathing and see the crystal open to allow you to step outside it, safe in the knowledge that you can return to it whenever you need to."),
    SpellModel.init(categoryId: 23, spellId: 75, spellName: "A Spell to Counter Another's Magic", spellContent: "Ingredients:\n\nTwo teaspoons of almond oil (or any suitable carrier oil)\nRosemary essential oil\nA mixing bottle\nA sheet of white paper\nA black ink pen\nA white altar candle\nA purple taper candle\nA fireproof bowl\n\nAdd three drops of the rosemary essential oil to the carrier oil and charge it by rolling the mixing bottle between the palms of your hands, focusing your thoughts on the purpose of your spell weaving. Now light the white candle and, focusing on its flame, see whoever you think is being negative towards you becoming smaller and smaller.\n\n\nAs this paper burns away,\nElements please hear me pray.\nTurn back the ill will sent to me,\nAnd send it on its way."),
    /// `Self Esteem Spells`
    SpellModel.init(categoryId: 24, spellId: 76, spellName: "Encourage Self Esteem", spellContent: "Ingredients:\n\nA bath!\nLavender essential oil\nJasmine essential oil\nAn essential oil burner\nSeven green oak leaves (or basil, if oak is out of season)\nOne purple candle\nOne yellow candle\nPurple thread\nAn envelope\n\nLight the candles, run a warm (not hot) bath, and drizzle some of the lavender oil into the water. Float the leaves in the bath and climb in. Breathe in through your nose and hold your breath for a count of seven. Breathe out through your mouth for a count of seven, and then seven more. When you breathe in, visualize your lungs filling up with warm, golden light. As you breathe out, see your frustrations in your breath and watch your anger, pain and any other barriers between you and the rest of the world leave you.\n\nSay the following words:\n\n\nI have a contribution to make.\nI have words to say.\nLet others hear the words I speak.\nAnd take self-doubt away.\nAnd let it be done, that it harm no one.\n\n\nRepeat the words six more times and when you feel ready, leave the bath and snuff out the candles in the usual way. Thread the oak (or basil) leaves on to the thread, hold them up to the light and repeat the words one more time. Now fold the leaves into the envelope and put them in your handbag or wallet. Whenever you have a bad day, first thing the following morning, heat the jasmine oil in the burner, re-light the candles and hold the leaves up to the flames, repeating the words seven times in all and face the new day with confidence."),
    /// `Travelling Spells`
    SpellModel.init(categoryId: 25, spellId: 77, spellName: "Nervous Travelling", spellContent: "Ingredients:\n\nA stone from your garden or from a local park\nA yellow taper candle\nLavender essential oil\nAn essential oil burner\nYellow acrylic paint\nViolet acrylic paint\nA paintbrush\n\nLight the yellow candle and oil burner. Facing east, paint the stone yellow. As the paint dries, visualize yourself arriving safely at your destination. Now paint a violet triangle with three equal sides on the stone, with a line just above the base line, joining the other two sides. This is the symbol alchemists use to represent air.\n\nThat done, face east and holding the stone in front of you at eye level repeat the following eight times:\n\n\nOh Guardian of the East,\nFill this stone with your blessing and protection.\nI pray for a safe journey to ..... for.....\nGuard .... and guide ...\nOn the path this journey takes,\nAnd see ....... home safely.\n\n\nAt the end of the eighth repetition say, ‘And let it be done, that it harm no one’ before performing closing rituals in the usual way.\n\nTake the stone with you whenever you travel.")
]

let HerbsAndOils: [[String:Any]] = [
    /// `A`
    ["alphabet": "A", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 0, herbOilName: "Alcohol abuse", ingredients: "Angelica"),
        HerbsAndOilsModel.init(herbOilId: 0, herbOilName: "Anexiety", ingredients: "Catnip\nFennel\nValerian\nWitch Hazel"),
        HerbsAndOilsModel.init(herbOilId: 0, herbOilName: "Arteriosclerosis", ingredients: "Hawthorn"),
        HerbsAndOilsModel.init(herbOilId: 0, herbOilName: "Arthritis", ingredients: "Garlic"),
        HerbsAndOilsModel.init(herbOilId: 0, herbOilName: "Asthma", ingredients: "Anise\nColtsfoot\nDaisy\nGarlic\nNettle")]],
    /// `B`
    ["alphabet": "B", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 5, herbOilName: "Bladder infection", ingredients: "Goldenrod"),
        HerbsAndOilsModel.init(herbOilId: 6, herbOilName: "Bronchitis", ingredients: "Angelica\nColtsfoot\nHorseradish"),
        HerbsAndOilsModel.init(herbOilId: 7, herbOilName: "Bruises", ingredients: "Aloe Vera\nComfrey\nShepherd’s Purse"),
        HerbsAndOilsModel.init(herbOilId: 8, herbOilName: "Burns", ingredients: "Aloe Vera\nComfrey")]],
    /// `C`
    ["alphabet": "C", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 9, herbOilName: "Cancer", ingredients: "Crimson Clover"),
        HerbsAndOilsModel.init(herbOilId: 10, herbOilName: "Chest complaints", ingredients: "Coltsfoot"),
        HerbsAndOilsModel.init(herbOilId: 11, herbOilName: "Colds", ingredients: "Blessed thistle\nElderflower\nHorehound"),
        HerbsAndOilsModel.init(herbOilId: 12, herbOilName: "Colic", ingredients: "Chamomile\nRosemary\nYarrow"),
        HerbsAndOilsModel.init(herbOilId: 13, herbOilName: "Constipation", ingredients: "Dandelion\nElderflower\nHorehound"),
        HerbsAndOilsModel.init(herbOilId: 14, herbOilName: "Cuts", ingredients: "Aloe Vera\nComfrey\nShepherd’s\nPurse")]],
    /// `D`
    ["alphabet": "D", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 15, herbOilName: "Delayed periods", ingredients: "Aloe Vera"),
        HerbsAndOilsModel.init(herbOilId: 16, herbOilName: "Depression", ingredients: "Lavender\nRosemary\nSaffron"),
        HerbsAndOilsModel.init(herbOilId: 17, herbOilName: "Diarrhea", ingredients: "Alder\nChamomile"),
        HerbsAndOilsModel.init(herbOilId: 18, herbOilName: "Dysentery", ingredients: "Comfrey")]],
    /// `E`
    ["alphabet": "E", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 19, herbOilName: "Eczema", ingredients: "Goldenseal\nWitch Hazel"),
        HerbsAndOilsModel.init(herbOilId: 20, herbOilName: "Edema", ingredients: "Hawthorn"),
        HerbsAndOilsModel.init(herbOilId: 21, herbOilName: "Emphysema", ingredients: "Coltsfoot"),
        HerbsAndOilsModel.init(herbOilId: 22, herbOilName: "Eye aliments", ingredients: "Eyebright")]],
    /// `F`
    ["alphabet": "F", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 23, herbOilName: "Fatigue", ingredients: "Lavender\nRosemary"),
        HerbsAndOilsModel.init(herbOilId: 24, herbOilName: "Fever", ingredients: "Catnip\nCoriander\nDogwood\nElderflower\nGinger\nHorseheal\nWormwood"),
        HerbsAndOilsModel.init(herbOilId: 25, herbOilName: "Flu", ingredients: "Cinnamon")]],
    /// `G`
    ["alphabet": "G", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 26, herbOilName: "Gallstones", ingredients: "Dandelions"),
        HerbsAndOilsModel.init(herbOilId: 27, herbOilName: "Gout", ingredients: "Strawberry Leaves"),
        HerbsAndOilsModel.init(herbOilId: 28, herbOilName: "Gum infections", ingredients: "Myrrh")]],
    /// `H`
    ["alphabet": "H", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 29, herbOilName: "Heamorrhoids", ingredients: "Elderflower"),
        HerbsAndOilsModel.init(herbOilId: 30, herbOilName: "Headaches", ingredients: "Lady’s Mantle\nLavender\nPeppermint\nThyme\nWillow Bark"),
        HerbsAndOilsModel.init(herbOilId: 31, herbOilName: "Heart conditions", ingredients: "Hawthorn\nRosemary"),
        HerbsAndOilsModel.init(herbOilId: 32, herbOilName: "Hypertension", ingredients: "Rosemary")]],
    /// `I`
    ["alphabet": "I", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 33, herbOilName: "Impotency", ingredients: "Elderflower\nGinseng\nJasmine\nLavender\nMandrake"),
        HerbsAndOilsModel.init(herbOilId: 34, herbOilName: "Infections", ingredients: "Dogwood\nGarlic\nMyrrh\nViolet"),
        HerbsAndOilsModel.init(herbOilId: 35, herbOilName: "Infertility", ingredients: "Mandrake"),
        HerbsAndOilsModel.init(herbOilId: 36, herbOilName: "Inflammations", ingredients: "Chickweed\nGoldenrod\nLady’s Mantle\nWitch Hazel"),
        HerbsAndOilsModel.init(herbOilId: 37, herbOilName: "Insomnia", ingredients: "Goldenrod\nPassion\nFlower\nValerian")]],
    /// `J`
    ["alphabet": "J", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 38, herbOilName: "Jaundice and liver disease", ingredients: "Agrimony\nDandelion\nRosemary\nYarrow")]],
    /// `K`
    ["alphabet": "K", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 39, herbOilName: "Kidney conditions", ingredients: "Horseradish"),
        HerbsAndOilsModel.init(herbOilId: 40, herbOilName: "Kidney stones", ingredients: "Rose")]],
    /// `L`
    ["alphabet": "L", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 41, herbOilName: "Lung infections", ingredients: "Nettle")]],
    /// `M`
    ["alphabet": "M", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 42, herbOilName: "Menopause", ingredients: "Lady’s Mantle"),
        HerbsAndOilsModel.init(herbOilId: 43, herbOilName: "Menstrual cramps", ingredients: "Catnip\nChamomile\nGinger\nLady’s Mantle\nPennyroyal"),
        HerbsAndOilsModel.init(herbOilId: 44, herbOilName: "Menstrual problems", ingredients: "Fennel"),
        HerbsAndOilsModel.init(herbOilId: 45, herbOilName: "Muscle aches", ingredients: "Nettle"),
        HerbsAndOilsModel.init(herbOilId: 46, herbOilName: "Muscle cramps", ingredients: "Peppermint")]],
    /// `N`
    ["alphabet": "N", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 47, herbOilName: "Nervous conditions", ingredients: "Chamomile"),
        HerbsAndOilsModel.init(herbOilId: 48, herbOilName: "Neuralgia", ingredients: "Juniper\nLavender")]],
    /// `P`
    ["alphabet": "P", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 49, herbOilName: "Pancreas problems", ingredients: "Dandelion"),
        HerbsAndOilsModel.init(herbOilId: 50, herbOilName: "Paralysis", ingredients: "Rosemary")]],
    /// `R`
    ["alphabet": "R", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 51, herbOilName: "Rheumatism", ingredients: "Garlic\nHorseradish\nJuniper\nLavender\nRosemary\nValerian"),
        HerbsAndOilsModel.init(herbOilId: 52, herbOilName: "Ringworm", ingredients: "Bloodroot\nGoldenseal")]],
    /// `S`
    ["alphabet": "S", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 53, herbOilName: "Skin irritation", ingredients: "Shepherd’s Purse"),
        HerbsAndOilsModel.init(herbOilId: 54, herbOilName: "Sore throats", ingredients: "Alder"),
        HerbsAndOilsModel.init(herbOilId: 55, herbOilName: "Sprains", ingredients: "Lavender"),
        HerbsAndOilsModel.init(herbOilId: 56, herbOilName: "Stomach ulcers and tumours", ingredients: "Adder’s Tongue\nComfrey\nNettle"),
        HerbsAndOilsModel.init(herbOilId: 57, herbOilName: "Stress", ingredients: "Rosemary\nValerian"),
        HerbsAndOilsModel.init(herbOilId: 58, herbOilName: "Swellings", ingredients: "Juniper\nValerian\nWitch Hazel")]],
    /// `T`
    ["alphabet": "T", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 59, herbOilName: "Tonsillitis", ingredients: "Mallow"),
        HerbsAndOilsModel.init(herbOilId: 60, herbOilName: "Toothaache", ingredients: "Aloe Vera"),
        HerbsAndOilsModel.init(herbOilId: 61, herbOilName: "Tuberculosis", ingredients: "Coltsfoot"),
        HerbsAndOilsModel.init(herbOilId: 62, herbOilName: "Tumours", ingredients: "Witch Hazel")]],
    /// `V`
    ["alphabet": "V", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 63, herbOilName: "Vertigo", ingredients: "Rosemary")]],
    /// `W`
    ["alphabet": "W", "herbsAndOils": [
        HerbsAndOilsModel.init(herbOilId: 64, herbOilName: "Warts", ingredients: "Milkweed"),
        HerbsAndOilsModel.init(herbOilId: 65, herbOilName: "Whooping cough", ingredients: "Thyme")]],
]

let Calender: [CalendarEventModel] = [
    CalendarEventModel.init(monthIndx: 1, monthName: "January", event: "Jan 1: Birthday of folklorist Sir James Frazier\nJan 13: Last of Austria’s witchcraft laws repealed in 1787\nJan 19: Birthday of Dorothy Clutterbuck\nJan 24: Sementivae, a festival celebrating the sowing of the fields for springtime\nJan 25: Birthday of poet Robert Burns\nJan 28: Full moon — Cold Moon or Wolf Moon. Maximize winter preparation of Great Work.\nJan 30: Beginning of Roman celebration of Februalia\nJan 31: Up Helly\nJan 31: Disablot, a Norse Heathen celebration to mark new beginnings"),
    CalendarEventModel.init(monthIndx: 2, monthName: "February", event: "Feb 2: Imbolc, the celebration of the goddess Brighid\nFeb 3: Welcome return of Maiden Goddess and Green Lord.\nFeb 12: Death of Gerald Gardner, founder of modern Wicca, in 1964\nFeb 13–21: Roman Festival of Parentalia\nFeb 15: Lupercalia, celebrating fertility and the coming of spring\nFeb 27: Full Moon — Quickening Moon, or Snow Moon "),
    CalendarEventModel.init(monthIndx: 3, monthName: "March", event: "Mar 1: Matronalia, the Festival of Women, held in honor of Juno Luciana.\nMar 6: Birthday of Laurie Cabot, who is considered to be the official witch of Salem in 1933\nMar 17: St. Patrick’s Day\nMar 20: Ostara, the spring equinox.\nMar 26: Birthday of Joseph Campbell\nMar 28: Death of Scott Cunningham, a famous author in 1993\nMar 28: Full moon — Storm Moon, Initiate spring germination of Great Work"),
    CalendarEventModel.init(monthIndx: 4, monthName: "April", event: "Apr 15: Sigrblot, a Norse Heathen celebration of the first day of summer \nApr 16: Birthday of author Margot Adler\nApr 26: Full moon — Wind Moon, also called the Pink Moon. Time for sacred union and divine marriage.\nApr 28–May 3: Floralia, honoring the goddess of spring flowers "),
    CalendarEventModel.init(monthIndx: 5, monthName: "May", event: "May 1: Beltane, A feast of fire and fertility\nMay 1: Samhain, The witches’ new year\nMay 5: Cinco de Mayo\nMay 26: Full moon — Flower Moon at 7:14 am. Complete spring germination of Great Work"),
    CalendarEventModel.init(monthIndx: 6, monthName: "June", event: "Jun 1: Witchcraft Act of 1563 goes into effect\nJun 7–15: Roman Festival of Vestalia, honoring the vestal virgins\nJun 10: Hanging of Bridget Bishop, twenty victims to be executed in the Salem Witch Trials.\nJun 13: Birthday of Gerald Gardner, founder of modern Wiccan,\nJun 19: Juneteenth\nJun 20: Litha, the summer solstice\nJun 20: Yule the winter solstice. Time to celebrate summer and welcome coming darkness.\nJun 22: England’s last Witchcraft Law is repealed in 1951\nJun 24: Full moon — Strong Sun Moon, Initiate summer’s cultivation of Great Work.\nJun 27: Birthday of author Scott Cunningham "),
    CalendarEventModel.init(monthIndx: 7, monthName: "July", event: "Jul 23: Full moon — Blessing Moon. Time to maximize summer’s cultivation of Great Work.\nJul 13: Birthday of Dr. John Dee in 1527\nJul 19: Rebecca Nurse is hanged in Salem, Massachusetts in 1692"),
    CalendarEventModel.init(monthIndx: 8, monthName: "August", event: "Aug 1: Lammas , the celebration of the grain harvest\nAug 1: Birthday of medium Edward Kelley, 1555\nAug 13: Roman Festival of Pomona,\nAug 20: Birthday of author Ann Moura in 1947\nAug 22: Full Moon – Corn Moon. Time to re-start summer’s cultivation of Great Work\nAug 23: Roman Festival of Vulcanalia\nAug 31: Birthday of author Raymond Buckland"),
    CalendarEventModel.init(monthIndx: 9, monthName: "September", event: "Sept 10: Birthday of Carl Llewellyn Weschcke\nSept 14: Birthday of Heinrich Cornelius Agrippa\nSept 20: Full Moon – Harvest Moon. Complete summer’s cultivation of Great Work\nSept 22: Mabon, the autumn equinox\nSept 22: Ostara (Southern Hemisphere), the spring equinox"),
    CalendarEventModel.init(monthIndx: 10, monthName: "Octomber", event: "Oct 12: Birthday of occultist Aleister Crowley, 1875\nOct 18: Birthday of Nicholas Culpeper, noted herbalist, in 1616\nOct 20: Full moon – Blood Moon. Begin autumn’s initiation of Great Work.\nOct 31: Samhain, the witches’ new year\nOct 31: Beltane a feast of fire and fertility\nOct 31: Covenant of the Goddess formed in 1975"),
    CalendarEventModel.init(monthIndx: 11, monthName: "November", event: "Nov 2: Birthday of Sirona Knight, a well known Wiccan author\nNov 6: Time for remembering your ancestors and divine funeral\nNov 19: Full moon – Mourning Moon. Make use of autumn’s integration of Great Work.\nNov 30: Birthday of Oberon Zell-Ravenheart, founder of Church of All Worlds\nNov 30: Festival of Hecate Trivia, honoring Hecate"),
    CalendarEventModel.init(monthIndx: 12, monthName: "December", event: "Dec 5: Krampusnacht, celebrating Krampus\nDec 17: Beginning of Saturnalia\nDec 18: Full moon – Long Nights Moon. Time to complete autumn’s integration of Great Work\nDec 21: Yule, the winter solstice\nDec 21: Litha the summer solstice\nDec 25: Feast of Frau Holle, Germanic goddess\nDec 25: Christmas Day"),
]


let CandleColour: [[String:Any]] = [
    /// `A`
    ["alphabet": "A", "diseases": [
        CandleColorModel.init(diseaseId: 0, diseaseName: "Allergies", candleColor: "Violet"),
        CandleColorModel.init(diseaseId: 1, diseaseName: "Anaemia", candleColor: "Red"),
        CandleColorModel.init(diseaseId: 2, diseaseName: "Anorexia", candleColor: "Aquamarine"),
        CandleColorModel.init(diseaseId: 3, diseaseName: "Anxiety", candleColor: "Rose"),
        CandleColorModel.init(diseaseId: 4, diseaseName: "Arthritis", candleColor: "Orange"),
        CandleColorModel.init(diseaseId: 5, diseaseName: "Asthma", candleColor: "Orange\nIndigo\nViolet")
        ]],
    
    /// `B`
    ["alphabet": "B", "diseases": [
        CandleColorModel.init(diseaseId: 0, diseaseName: "Baldness", candleColor: "Violet"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Blood clots", candleColor: "Violet"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Boils", candleColor: "Green"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Bulimia", candleColor: "Aquamarine"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Burns", candleColor: "Aquamarine\nBlue"),
        ]],
    
    /// `C`
    ["alphabet": "C", "diseases": [
        CandleColorModel.init(diseaseId: 0, diseaseName: "Colds", candleColor: "Green\nViolet"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Constipation", candleColor: "Orange\nYellow\nRose"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Coughs", candleColor: "Orange"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Cuts", candleColor: "Blue"),
        ]],
    
    /// `D`
    ["alphabet": "D", "diseases": [
        CandleColorModel.init(diseaseId: 0, diseaseName: "Deafness", candleColor: "Indigo"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Dementia", candleColor: "Indigo"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Depression", candleColor: "Orange\nIndigo\nRose"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Diabetes", candleColor: "Yellow"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Diarrhea", candleColor: "Blue"),
        ]],
    
    /// `E`
    ["alphabet": "E", "diseases": [
        CandleColorModel.init(diseaseId: 0, diseaseName: "Epilepsy", candleColor: "Orange\nIndigo"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Exhaustion", candleColor: "Orange"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Eye ailments", candleColor: "Aquamarine\nIndigo"),
        ]],
    
    /// `F`
    ["alphabet": "F", "diseases": [
        CandleColorModel.init(diseaseId: 23, diseaseName: "Fever", candleColor: "Blue"),
        CandleColorModel.init(diseaseId: 24, diseaseName: "Fractures", candleColor: "White"),
        ]],
    
    /// `G`
    ["alphabet": "G", "diseases": [
        CandleColorModel.init(diseaseId: 25, diseaseName: "Gout", candleColor: "Violet"),
        ]],
    
    /// `H`
    ["alphabet": "H", "diseases": [
        CandleColorModel.init(diseaseId: 0, diseaseName: "Headaches", candleColor: "Green\nBlue"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Hearing loss", candleColor: "Rose"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Heartburn", candleColor: "Yellow"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Heart conditions", candleColor: "Rose"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Hypersensitivity", candleColor: "Aquamarine"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Hypertension", candleColor: "Green\nAquamarine\nBlue"),
        ]],
    
    /// `I`
    ["alphabet": "I", "diseases": [
        CandleColorModel.init(diseaseId: 0, diseaseName: "Indigestion", candleColor: "Yellow"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Infections", candleColor: "Aquamarine\nIndigo"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Inflammations", candleColor: "Aquamarine"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Insomnia", candleColor: "Blue"),
        ]],
    
    /// `K`
    ["alphabet": "K", "diseases": [
        CandleColorModel.init(diseaseId: 0, diseaseName: "Kidney ailments", candleColor: "Green\nRose"),
        ]],
    
    /// `L`
    ["alphabet": "L", "diseases": [
        CandleColorModel.init(diseaseId: 37, diseaseName: "Leukaemia", candleColor: "Red"),
        CandleColorModel.init(diseaseId: 38, diseaseName: "Liver infections", candleColor: "Red"),
        ]],
    
    /// `M`
    ["alphabet": "M", "diseases": [
        CandleColorModel.init(diseaseId: 0, diseaseName: "Menstrual cramps", candleColor: "Yellow\nBlue"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Mental conditions", candleColor: "Indigo\nViolet"),
        ]],
    
    /// `N`
    ["alphabet": "N", "diseases": [
        CandleColorModel.init(diseaseId: 0, diseaseName: "Nervous conditions", candleColor: "Green\nIndigo"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Neuralgia", candleColor: "Red"),
        ]],
    
    /// `P`
    ["alphabet": "P", "diseases": [
        CandleColorModel.init(diseaseId: 43, diseaseName: "Paralysis", candleColor: "Red"),
        CandleColorModel.init(diseaseId: 44, diseaseName: "Parkinson’s disease", candleColor: "Indigo"),
        CandleColorModel.init(diseaseId: 45, diseaseName: "Pneumonia", candleColor: "Indigo"),
        ]],
    
    /// `S`
    ["alphabet": "S", "diseases": [
        CandleColorModel.init(diseaseId: 0, diseaseName: "Sinus problems", candleColor: "Violet"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Skin conditions", candleColor: "Yellow\nAquamarine"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Skin rashes", candleColor: "Blue"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Sore throat", candleColor: "Blue"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Stress", candleColor: "Violet"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Stroke", candleColor: "White"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Sunburn", candleColor: "Blue"),
        ]],
    
    /// `T`
    ["alphabet": "T", "diseases": [
        CandleColorModel.init(diseaseId: 53, diseaseName: "Tuberculosis", candleColor: "Indigo"),
        CandleColorModel.init(diseaseId: 54, diseaseName: "Tumours", candleColor: "Violet"),
        ]],
    
    /// `U`
    ["alphabet": "U", "diseases": [
        CandleColorModel.init(diseaseId: 0, diseaseName: "Ulcers", candleColor: "Green\nBlue"),
        CandleColorModel.init(diseaseId: 0, diseaseName: "Upset stomach", candleColor: "Indigo"),
        ]],
]

let LunarCalener: [LunarCalenderModel] = [
    LunarCalenderModel.init(lunarId: 0, lunarName: "Aries", lunarDate: "(21 March - 20 April)", signDesc: "Aries is the first sign and full of ideals and enthusiasm.Aries is the perfect time for spells concerning new beginnings."),
    LunarCalenderModel.init(lunarId: 1, lunarName: "Taurus", lunarDate: "(21 April - 20 May)", signDesc: "Taurus is the sign of Venus, the Roman goddess of love and beauty. This is the perfect time to use your love spells to take advantage of Venus."),
    LunarCalenderModel.init(lunarId: 2, lunarName: "Gemini", lunarDate: "(21 May - 21 June)", signDesc: "Gemini is ruled by the planet Mercury, which makes them fast, witty and super into communications. Words are their weapon of choice. It is the best time for those with writing projects to use spells to improvise their talent."),
    LunarCalenderModel.init(lunarId: 3, lunarName: "Cancer", lunarDate: "(22 June - 22 July)", signDesc: "Cancer is primarily known for being emotional, nurturing, and highly intuitive, as well as sensitive and at times insecure. This is the best time to cast spells related to love, relationships, friendships and prosperity."),
    LunarCalenderModel.init(lunarId: 4, lunarName: "Leo", lunarDate: "(23 July - 22 August)", signDesc: "Leo is ruled by the sun and Leos are renowned for their stability, loyalty, and consistency. It is the best time for those who seek career and job growth, prosperity, and strengthening their relationships."),
    LunarCalenderModel.init(lunarId: 5, lunarName: "Virgo", lunarDate: "(23 August - 22 September)", signDesc: "Those born under the Virgo sign are known to be kind, gentle, and supportive friends and lovers who use their incredible intellect and resourcefulness to problem-solve. It is the best time to use spells to solve your personal and professional problems."),
    LunarCalenderModel.init(lunarId: 6, lunarName: "Libra", lunarDate: "(23 Sepetember - 22 Octomber)", signDesc: "Libra are beautiful and charming. They like to have things in place and make them orderly. They are generally well balanced and can see both sides of an argument. This is the best time to cast spells on legal and personal issues, resolving quarrels and starting things afresh."),
    LunarCalenderModel.init(lunarId: 7, lunarName: "Scorpio", lunarDate: "(23 Octomber - 22 November)", signDesc: "Scorpios are full of passion and have a thirst for power. They are very emotional and expect reciprocal passion and loyalty from their lovers. This is the best time to cast spells to attract someone you love closer to you, cementing your love relationship and creating passion and romance."),
    LunarCalenderModel.init(lunarId: 8, lunarName: "Sagittarius", lunarDate: "(23 November - 22 December)", signDesc: "Sagittarius are always positive, have a great sense of humor along with being fair and honest. They are great at making conversations and are lovers of adventure and travel. This is the best time to cast spells for those interested in exploration and travel."),
    LunarCalenderModel.init(lunarId: 9, lunarName: "Capricorn", lunarDate: "(22 December - 20 January)", signDesc: "Capricon are very ambitious and are willing to go the extra mile to achieve their goals. They can be workaholics and like to approach problems in a practical manner. This is the best time to cast spells related to career growth, prosperity and getting a new job."),
    LunarCalenderModel.init(lunarId: 10, lunarName: "Aquarius", lunarDate: "(21 January - 19 February)", signDesc: "Aquarius is known for being idealistic, progressive, intellectual and creative. This is a great time to use spells to make new friends, unleash your creative side and ponder about problems that have been bothering you for a long time."),
    LunarCalenderModel.init(lunarId: 11, lunarName: "Pisces", lunarDate: "(20 February - 20 March)", signDesc: "Pisces are the most artistic of all zodiac signs. They have strong imaginations, and are known for pursuing hobbies such as art, music, and writing. This the best time to cast spells for those who are creative.")
]
